---
name: Build OCI Container
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci*
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  # Pre-Action Stage
  pre-build:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-start.yml@master
    secrets: inherit

  # Build Stage
  build-and-push:
    runs-on: ubuntu-latest
    needs: [pre-build]
    env:
      DOCKER_FILE: Dockerfile
      IMAGE_NAME: dae-docs
      IMAGE_TAG: v1
    outputs:
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ github.head_ref || github.ref_name }}-${{ steps.export_commit_sha.outputs.sha_short }}-${{ github.run_number }}
    steps:
      - uses: actions/checkout@master
      - name: Get HEAD git sha
        id: export_commit_sha
        run: |
          echo "sha_long=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}
          tag: ${{ github.head_ref || github.ref_name }}-${{ steps.export_commit_sha.outputs.sha_short }}-${{ github.run_number }}
          tag_with_latest: true
          cache: true
          cache_registry: quay.io/${{ github.repository_owner }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-${{ steps.export_commit_sha.outputs.sha_short }}-${{ github.run_number }}"


  # Post-Action Stage
  post-build:
    needs: [pre-build,build-and-push]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-result.yml@master
    with:
      IMAGE_NAME: ${{ needs.build-and-push.outputs.image_name }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}
      SHA_SHORT: ${{ needs.pre-build.outputs.git_sha_short }}
    secrets: inherit
