---
name: Build OCI Container
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci*
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  # Pre-Action Stage
  export-metadata:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/export-metadata.yml@master
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.after }}
      fetch-depth: 0

  notify-build-start:
    needs: [export-metadata]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-start.yml@master
    with:
      git_sha_long: ${{ needs.export-metadata.outputs.git_sha_long }}
      git_sha_short: ${{ needs.export-metadata.outputs.git_sha_short }}
      git_commit_msg: ${{ needs.export-metadata.outputs.git_commit_msg }}
    secrets: inherit

  # Build Stage
  build-and-push:
    runs-on: ubuntu-latest
    needs: [notify-build-start]
    env:
      DOCKER_FILE: Dockerfile
      IMAGE_NAME: dae-docs
      IMAGE_TAG: ${{ github.head_ref || github.ref_name }}-${{ needs.export-metadata.outputs.git_sha_short }}-${{ github.run_number }}
    outputs:
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ env.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}
          tag: ${{ env.IMAGE_TAG }}
          tag_with_latest: true
          cache: true
          cache_registry: quay.io/${{ github.repository_owner }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"


  # Post-Action Stage
  notify-build-result:
    needs: [notify-build-start,build-and-push]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-result.yml@master
    with:
      IMAGE_NAME: ${{ needs.build-and-push.outputs.image_name }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}
      SHA_SHORT: ${{ needs.export-metadata.outputs.git_sha_short }}
    secrets: inherit
