#      _                      _
#   __| | __ _  ___        __| | ___   ___ ___
#  / _` |/ _` |/ _ \_____ / _` |/ _ \ / __/ __|
# | (_| | (_| |  __/_____| (_| | (_) | (__\__ \
#  \__,_|\__,_|\___|      \__,_|\___/ \___|___/
# 
#
# Copyright (C) 2023 @daeuniverse <https://github.com/daeuniverse>
#
# This is a open-source software, liscensed under the MIT License.
# See /License for more information.

---
name: Build OCI Container (Prod)
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'release/**'

jobs:
  # Pre-Action Stage
  pre-actions:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/pre-actions.yml@master
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      fetch-depth: 0
    secrets: inherit

  # Build Stage
  build-and-push:
    runs-on: ubuntu-latest
    needs: [pre-actions]
    env:
      dockerfile: Dockerfile
      image_tag: prod-${{ needs.pre-actions.outputs.git_sha_short }}-${{ github.run_number }}
    outputs:
      image_tag: ${{ env.image_tag }}
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ github.repository }}
          build_file: ${{ env.dockerfile }}
          tag: ${{ env.image_tag }}
          tag_with_latest: true
          cache: true
          cache_registry: quay.io/${{ github.repository_owner }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ github.repository }}:${{ env.image_tag }}"

  post-actions:
    needs: [pre-actions,build-and-push]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/post-actions.yml@master
    with:
      image: ${{ github.repository }}
      image_tag: ${{ needs.build-and-push.outputs.image_tag }}
      sha_short: ${{ needs.pre-actions.outputs.git_sha_short }}
    secrets: inherit

